#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef FORTERSDK_SWIFT_H
#define FORTERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#import <ForterSDK/ForterSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ForterSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class FTREventBase;
@class NSString;

SWIFT_PROTOCOL("_TtP9ForterSDK19EventBufferProtocol_")
@protocol EventBufferProtocol
- (void)queueEvent:(FTREventBase * _Nullable)event;
- (void)queueEvent:(FTREventBase * _Nullable)event withCallbackBlock:(void (^ _Nonnull)(BOOL, NSString * _Nonnull))withCallbackBlock;
- (NSInteger)eventsInBufferCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendAllEvents SWIFT_WARN_UNUSED_RESULT;
- (void)sendAllEvents:(void (^ _Nonnull)(BOOL, NSString * _Nonnull))callbackBlock;
- (void)reset;
@end

enum FTROptFlag : NSInteger;

SWIFT_CLASS("_TtC9ForterSDK18FTRAppActivePlugin")
@interface FTRAppActivePlugin : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull pluginName;)
+ (NSString * _Nonnull)pluginName SWIFT_WARN_UNUSED_RESULT;
+ (void)setPluginName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum FTROptFlag optFlag;)
+ (enum FTROptFlag)optFlag SWIFT_WARN_UNUSED_RESULT;
+ (void)setOptFlag:(enum FTROptFlag)value;
- (BOOL)register SWIFT_WARN_UNUSED_RESULT;
- (BOOL)unregister SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FTRRTFeature;

SWIFT_PROTOCOL("_TtP9ForterSDK24FTRConfigurationProtocol_")
@protocol FTRConfigurationProtocol
@property (nonatomic, copy) NSString * _Nullable siteId;
@property (nonatomic, copy) NSString * _Nullable deviceUid;
@property (nonatomic, copy) NSString * _Nullable accountId;
- (FTRRTFeature * _Nullable)getFeatureByName:(NSString * _Nonnull)featureName SWIFT_WARN_UNUSED_RESULT;
@end

@class FTRSDKConfiguration;

SWIFT_CLASS("_TtC9ForterSDK23FTRConfigurationManager")
@interface FTRConfigurationManager : NSObject <FTRConfigurationProtocol>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull deviceUniqueIdentifierDidChange;)
+ (NSNotificationName _Nonnull)deviceUniqueIdentifierDidChange SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull accountIdentifierDidChange;)
+ (NSNotificationName _Nonnull)accountIdentifierDidChange SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceUID;)
+ (NSString * _Nonnull)deviceUID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull accountUID;)
+ (NSString * _Nonnull)accountUID SWIFT_WARN_UNUSED_RESULT;
+ (void)with:(id <FTRConfigurationProtocol> _Nonnull)nsRTConfiguration :(FTRSDKConfiguration * _Nonnull)nsSDKConfiguration;
+ (FTRConfigurationManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRtConfiguration:(id <FTRConfigurationProtocol> _Nonnull)rtConfiguration sdkConfiguration:(FTRSDKConfiguration * _Nonnull)sdkConfiguration OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nullable siteId;
@property (nonatomic, copy) NSString * _Nullable deviceUid;
@property (nonatomic, copy) NSString * _Nullable accountId;
- (FTRRTFeature * _Nullable)getFeatureByName:(NSString * _Nonnull)featureName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9ForterSDK21FTRDataPluginsManager")
@interface FTRDataPluginsManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FTRDataPluginsManager * _Nonnull shared;)
+ (FTRDataPluginsManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)registerPlugins;
@end


SWIFT_PROTOCOL("_TtP9ForterSDK19FTREventApiProtocol_")
@protocol FTREventApiProtocol
- (void)sendEvent:(FTREventBase * _Nullable)event;
- (void)sendEvents:(NSArray<FTREventBase *> * _Nonnull)events;
- (BOOL)flush SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)eventsInBufferCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)reset SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9ForterSDK11FTREventApi")
@interface FTREventApi : NSObject <FTREventApiProtocol>
+ (FTREventApi * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)with:(id <EventBufferProtocol> _Nonnull)eventBuffer;
- (void)sendEvent:(FTREventBase * _Nullable)event;
- (void)sendEvents:(NSArray<FTREventBase *> * _Nonnull)events;
- (BOOL)flush SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)eventsInBufferCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)reset SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9ForterSDK21FTREventDiskIntegrity")
@interface FTREventDiskIntegrity : FTREventBase
- (void)selfPopulateProperties;
@property (nonatomic, readonly, copy) NSString * _Nullable eventType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK25FTREventEmbeddedProvision")
@interface FTREventEmbeddedProvision : FTREventBase
- (void)selfPopulateProperties;
@property (nonatomic, readonly, copy) NSString * _Nonnull eventType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDictionary;
@class NSURLSessionTaskTransactionMetrics;
@class VideoEncoderInfoEntity;

SWIFT_PROTOCOL("_TtP9ForterSDK23FTREventFactoryProtocol_")
@protocol FTREventFactoryProtocol
- (FTREventBase * _Nullable)generateNavigationTrackEvent:(FTRSDKNavigationType)navigationType screenName:(NSString * _Nonnull)screenName pageId:(NSString * _Nonnull)pageId pageCategory:(NSString * _Nonnull)pageCategory otherInfo:(NSString * _Nonnull)otherInfo SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateAppActiveEvent SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateNetworkEvent SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateTrackEvent:(FTRSDKActionType)trackType trackMessage:(NSString * _Nullable)trackMessage trackDictionary:(NSDictionary * _Nullable)trackDictionary SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateErrorEvent:(NSString * _Nonnull)errorMessage errorData:(NSDictionary * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateLocationEventWithLatitude:(double)latitude longtitude:(double)longtitude altitude:(double)altitude SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateNetworkMetricsEvent:(NSURLSessionTaskTransactionMetrics * _Nonnull)metrics SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateVideoEncodersEventWithEncoders:(NSArray<VideoEncoderInfoEntity *> * _Nonnull)encoders SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generatePhotoEventWithData:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateDiskIntegrityEventWithPrebootUID:(NSString * _Nonnull)prebootUID integrityIndicators:(NSArray<NSString *> * _Nonnull)integrityIndicators SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateEmbeddedProvisionsEventWithData:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateQuagoEventWithPayload:(NSString * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9ForterSDK15FTREventFactory")
@interface FTREventFactory : NSObject <FTREventFactoryProtocol>
/// Initialize the shared instance with the provided <code>nsInstance</code>.
+ (void)with:(id <FTREventFactoryProtocol> _Nonnull)nsInstance;
+ (id <FTREventFactoryProtocol> _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateNavigationTrackEvent:(FTRSDKNavigationType)navigationType screenName:(NSString * _Nonnull)screenName pageId:(NSString * _Nonnull)pageId pageCategory:(NSString * _Nonnull)pageCategory otherInfo:(NSString * _Nonnull)otherInfo SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateAppActiveEvent SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateNetworkEvent SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateTrackEvent:(FTRSDKActionType)trackType trackMessage:(NSString * _Nullable)trackMessage trackDictionary:(NSDictionary * _Nullable)trackDictionary SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateErrorEvent:(NSString * _Nonnull)errorMessage errorData:(NSDictionary * _Nullable)errorData SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateLocationEventWithLatitude:(double)latitude longtitude:(double)longtitude altitude:(double)altitude SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateNetworkMetricsEvent:(NSURLSessionTaskTransactionMetrics * _Nonnull)metrics SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateVideoEncodersEventWithEncoders:(NSArray<VideoEncoderInfoEntity *> * _Nonnull)encoders SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generatePhotoEventWithData:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateDiskIntegrityEventWithPrebootUID:(NSString * _Nonnull)prebootUID integrityIndicators:(NSArray<NSString *> * _Nonnull)integrityIndicators SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateEmbeddedProvisionsEventWithData:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FTREventBase * _Nullable)generateQuagoEventWithPayload:(NSString * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9ForterSDK14FTREventPhotos")
@interface FTREventPhotos : FTREventBase
- (void)selfPopulateProperties;
@property (nonatomic, readonly, copy) NSString * _Nullable eventType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK13FTREventQuago")
@interface FTREventQuago : FTREventBase
- (void)selfPopulateProperties;
@property (nonatomic, readonly, copy) NSString * _Nullable eventType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK21FTREventVideoEncoders")
@interface FTREventVideoEncoders : FTREventBase
- (void)selfPopulateProperties;
@property (nonatomic, readonly, copy) NSString * _Nullable eventType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK12FTRFileUtils")
@interface FTRFileUtils : NSObject
+ (NSString * _Nullable)getAppInstallTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FTRListener;
@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC9ForterSDK18FTRLocationManager")
@interface FTRLocationManager : NSObject <CLLocationManagerDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)didUpdateLocationRegisterWithListener:(FTRListener * _Nonnull)listener;
- (void)didUpdateLocationUnregisterWithListener:(FTRListener * _Nonnull)listener;
- (void)registerWithAccuracy:(double)accuracy filter:(double)filter;
- (void)unregister;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC9ForterSDK17FTRLocationPlugin")
@interface FTRLocationPlugin : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull pluginName;)
+ (NSString * _Nonnull)pluginName SWIFT_WARN_UNUSED_RESULT;
+ (void)setPluginName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum FTROptFlag optFlag;)
+ (enum FTROptFlag)optFlag SWIFT_WARN_UNUSED_RESULT;
+ (void)setOptFlag:(enum FTROptFlag)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval defaultLocationQueryIntervalSeconds;)
+ (NSTimeInterval)defaultLocationQueryIntervalSeconds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultLocationAccuracy;)
+ (double)defaultLocationAccuracy SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double defaultLocationFilter;)
+ (double)defaultLocationFilter SWIFT_WARN_UNUSED_RESULT;
- (BOOL)register SWIFT_WARN_UNUSED_RESULT;
- (BOOL)unregister SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK21FTRMobileUIDGenerator")
@interface FTRMobileUIDGenerator : NSObject
+ (NSString * _Nonnull)generate SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)installationGUID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, FTROptFlag, closed) {
  FTROptFlagOptIn = 0,
  FTROptFlagOptOut = 1,
};


SWIFT_CLASS("_TtC9ForterSDK14FTRPhotoPlugin")
@interface FTRPhotoPlugin : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK14FTRQuagoPlugin")
@interface FTRQuagoPlugin : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FTRRTFeatureFlag;

SWIFT_CLASS("_TtC9ForterSDK12FTRRTFeature")
@interface FTRRTFeature : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull featureName;
@property (nonatomic, readonly, copy) NSString * _Nonnull featureType;
@property (nonatomic, readonly) NSInteger priority;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, FTRRTFeatureFlag *> * _Nonnull keysOverride;
- (BOOL)isFeatureEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isFeatureDisabled SWIFT_WARN_UNUSED_RESULT;
- (FTRRTFeatureFlag * _Nullable)getFlagWithFlagName:(NSString * _Nonnull)flagName SWIFT_WARN_UNUSED_RESULT;
+ (FTRRTFeature * _Nullable)fromResponse:(NSDictionary * _Nonnull)response SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK16FTRRTFeatureFlag")
@interface FTRRTFeatureFlag : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull flagKey;
@property (nonatomic, readonly, strong) NSObject * _Nonnull flagValue;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key value:(NSObject * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isDisabled SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, FTRSDKState, closed) {
  FTRSDKStateInactive = 0,
  FTRSDKStateStarting = 1,
  FTRSDKStateActive = 2,
  FTRSDKStateInvalidConf = 3,
  FTRSDKStateError = 4,
  FTRSDKStateDestroyed = 5,
};

@class NSUUID;

SWIFT_CLASS("_TtC9ForterSDK21FTRSDKStateListenable")
@interface FTRSDKStateListenable : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FTRSDKStateListenable * _Nonnull shared;)
+ (FTRSDKStateListenable * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum FTRSDKState value;
- (NSUUID * _Nonnull)addListener:(void (^ _Nonnull)(enum FTRSDKState))listener SWIFT_WARN_UNUSED_RESULT;
- (void)removeListenerWithId:(NSUUID * _Nonnull)id;
- (void)onState:(enum FTRSDKState)state block:(void (^ _Nonnull)(void))block;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ForterSDK17FTRSessionTracker")
@interface FTRSessionTracker : NSObject
- (void)setUserId:(NSString * _Nonnull)userId;
- (void)setAuthToken:(NSString * _Nonnull)authToken;
- (void)onSDKInitCalled;
- (void)onConfigurationStatusChangedWithStatus:(SessionPhaseStatus)status;
- (void)onEventSendingStatusChangedWithStatus:(SessionPhaseStatus)status;
- (NSString * _Nonnull)getUserId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAuthToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSessionToken SWIFT_WARN_UNUSED_RESULT;
- (void)registerListener:(FTRListener * _Nonnull)listener;
- (void)unregisterListener:(FTRListener * _Nonnull)listener;
- (void)clear;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FTRSessionTracker * _Nonnull instance;)
+ (FTRSessionTracker * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ForterSDK22FTRVideoEncodersPlugin")
@interface FTRVideoEncodersPlugin : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull pluginName;)
+ (NSString * _Nonnull)pluginName SWIFT_WARN_UNUSED_RESULT;
+ (void)setPluginName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum FTROptFlag optFlag;)
+ (enum FTROptFlag)optFlag SWIFT_WARN_UNUSED_RESULT;
+ (void)setOptFlag:(enum FTROptFlag)value;
- (BOOL)register SWIFT_WARN_UNUSED_RESULT;
- (BOOL)unregister SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ForterSDK13FTRXrayPlugin")
@interface FTRXrayPlugin : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP9ForterSDK23ForterAnalyticsProtocol_")
@protocol ForterAnalyticsProtocol
- (void)generateAnalyticsEvents;
@end


SWIFT_CLASS("_TtC9ForterSDK15ForterAnalytics")
@interface ForterAnalytics : NSObject <ForterAnalyticsProtocol>
+ (id <ForterAnalyticsProtocol> _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)with:(id <ForterAnalyticsProtocol> _Nonnull)nsForterAnalatics;
- (nonnull instancetype)initWithNsInstance:(id <ForterAnalyticsProtocol> _Nonnull)nsInstance OBJC_DESIGNATED_INITIALIZER;
- (void)generateAnalyticsEvents;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC9ForterSDK22VideoEncoderInfoEntity")
@interface VideoEncoderInfoEntity : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP9ForterSDK12XrayProtocol_")
@protocol XrayProtocol
- (void)run:(FTRRTFeature * _Nonnull)feature;
@end


SWIFT_CLASS("_TtC9ForterSDK4Xray")
@interface Xray : NSObject <XrayProtocol>
+ (id <XrayProtocol> _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)with:(id <XrayProtocol> _Nonnull)nsXray;
- (nonnull instancetype)initWithNsXray:(id <XrayProtocol> _Nonnull)nsXray OBJC_DESIGNATED_INITIALIZER;
- (void)run:(FTRRTFeature * _Nonnull)feature;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
